In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [4]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [5]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [6]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [7]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [8]:
reg.intercept_


0.29603261264909486

Calculate R-Squared

In [23]:
rsq = reg.score(x,y)
rsq

0.40668119528142843

Adjusted R-Squared

In [16]:
### Formula for adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

SyntaxError: invalid syntax (Temp/ipykernel_3996/3011013020.py, line 3)

In [17]:
x.shape

(84, 2)

In [34]:
arsq = 1 - (1 - rsq) * (84-1)/(84-2-1)
arsq

0.39203134825134023

In [30]:
n = x.shape[0]
p = x.shape[1]

In [35]:
arsq = 1 - (1 - rsq) * (n-1) / (n-p-1)
arsq

0.39203134825134023

In [36]:
from sklearn.feature_selection import f_regression

In [38]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [40]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [41]:
p_values.round(3)

array([0.   , 0.676])

In [42]:
reg_summary = pd.DataFrame(data = ['SAT', 'Rand 1,2,3'], columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [45]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [47]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676